---
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.21.0
    hooks:
      - id: yamllint
        args: ["-d {extends: relaxed, rules: {line-length: {max: 89}}}"]
  # Docker
  - repo: https://github.com/CoRfr/dockerfile-pre-commit
    rev: "fd7dca7bc1b4739848e05011899037157b3862e4"
    hooks:
      - id: dockerlint
        args:
          - --ignore=DL3003
          - --ignore=DL3008
          - --ignore=DL4005
  # Python
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          - --ignore=W503,W605,E501,E203
          - --max-line-length=89
  - repo: https://github.com/prettier/prettier
    rev: "2.0.5"
    hooks:
      - id: prettier
